---
- name: 4.1 Worker Node Configuration Files
  block:
    - name: 4.1.1-4.1.2 Ensure that the kubelet service file permissions are set to 600 or more restrictive and file ownership is set to root:root
      file:
        path: /lib/systemd/system/kubelet.service
        mode: '0600'
        owner: root
        group: root
      notify: restart kubelet

    - name: Check if proxy kubeconfig file exists
      stat:
        path: /etc/kubernetes/proxy.conf
      register: proxy_conf_stat

    - name: 4.1.3-4.1.4 If proxy kubeconfig file exists ensure permissions are set to 600 or more restrictive and file ownership is set to root:root
      file:
        path: /etc/kubernetes/proxy.conf
        mode: '0600'
        owner: root
        group: root
      when: proxy_conf_stat.stat.exists
      notify: restart kubelet

    - name: 4.1.5-4.1.6 Ensure that the --kubeconfig kubelet.conf file permissions are set to 600 or more restrictive and file ownership is set to root:root
      file:
        path: /etc/kubernetes/kubelet.conf
        mode: '0600'
        owner: root
        group: root
      notify: restart kubelet

    - name: 4.1.7-4.1.8 Ensure that the certificate authorities file permissions are set to 600 or more restrictive and file ownership is set to root:root
      file:
        path: /etc/kubernetes/pki/ca.crt
        mode: '0600'
        owner: root
        group: root
      notify: restart kubelet

    - name: 4.1.9-4.1.10 If the kubelet config.yaml configuration file is being used validate permissions set to 600 or more restrictive and file ownership is set to root:root
      file:
        path: /var/lib/kubelet/config.yaml
        mode: '0600'
        owner: root
        group: root
      notify: restart kubelet

  rescue:
    - name: Handle errors
      debug:
        msg: "Worker Node Configuration Files configuration failed: {{ ansible_failed_result }}"
      failed_when: true
