---
- name: 4.2 Kubelet
  block:
    - name: 4.2.1-4.2.13 Configure kubelet with secure settings
      template:
        src: templates/kubelet-config.yaml.j2
        dest: /var/lib/kubelet/config.yaml
        mode: '0600'
        owner: root
        group: root
      notify: restart kubelet

  rescue:
    - name: Handle errors
      debug:
        msg: "Kubelet configuration failed: {{ ansible_failed_result }}"
      failed_when: true
