- name: 1.3. Controller Manager
  block:
    - name: 1.3.1-1.3.7 Configure Controller Manager with secure settings
      template:
        src: templates/kube-controller-manager.yaml.j2
        dest: /etc/kubernetes/manifests/kube-controller-manager.yaml
        mode: '0600'
        owner: root
        group: root
      notify: restart kubelet

  rescue:
    - name: Handle errors
      debug:
        msg: "Controller Manager configuration failed: {{ ansible_failed_result }}"
      failed_when: true
