---
- name: 1 - Host Configuration
  block:
    - name: 1.1.2 - Ensure only trusted users are allowed to control Docker daemon (manual check)
      group:
        name: docker
        state: present

    - name: 1.1.3-1.1.18 - Ensure auditing is configured for Docker files and directories
      block:
        - name: Install auditd package
          package:
            name: auditd
            state: present

        - name: Enable auditd service
          service:
            name: auditd
            enabled: yes
            state: started

        - name: Configure auditd rules for Docker
          template:
            src: templates/docker-audit.rules.j2
            dest: /etc/audit/rules.d/docker.rules
            mode: '0640'
            owner: root
            group: root
          notify: restart auditd

    - name: 1.2.2 - Ensure that the version of Docker is up to date
      package:
        name: docker-ce
        state: latest
      register: docker_update
      notify: restart docker
  rescue:
    - name: Handle errors
      debug:
        msg: "Host Configuration failed: {{ ansible_failed_result }}"
      failed_when: true
